steps:
  - name: gcr.io/cloud-builders/gcloud
    args:
      - functions
      - deploy
      - --trigger-http # HTTP trigger
      - --runtime=nodejs16
      - --entry-point=entry # Defined function in index.js
      - --allow-unauthenticated # Enable anonymous access
      - almanac # Cloud Function name
